config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'user/registrations' }

  resources :tests, param: :test_id, only: :index do
    member do
      post :start
    end
  end

  resources :tests_passages, param: :tests_passage_id, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    root to: 'tests#index'
    resources :tests, param: :test_id do
      member do
        resources :questions, shallow: true, param: :question_id, except: :index do
          member do
            resources :answers, shallow: true, param: :answer_id, except: :index
          end
        end
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/models/tests_passage.rb
class TestsPassage < ApplicationRecord
  belongs_to :user
  belongs_to :test
  belongs_to :current_question, class_name: 'Question',
                                foreign_key: 'current_question_id',
                                optional: true

  before_validation :before_validation_set_first_question, on: :create
  before_validation :before_validation_set_next_question, on: :update

  def accept!(answer_ids)
    true_ids = current_question.answers.with_true_correctness.ids
    self.correct_questions += 1 if true_ids - answer_ids == answer_ids - true_ids

    save!
  end

  def completed?
    current_question.nil?
  end

  def num
    @num ||= init_num
  end

  def percentage
    (correct_questions.to_f / num[:questions]) * 100
  end

  def passed?
    percentage >= Test::ACCEPTABLE_PERCENTAGE
  end

  private

  def before_validation_set_first_question
    self.current_question = test.questions.first
  end

  def before_validation_set_next_question
    self.current_question =
      test.ordered_questions.where('id > ?', current_question.id).first
  end

  def init_num
    @num = {}
    @num[:questions] = test.questions.count

    if completed?
      @num[:completed_questions] = @num[:questions]
    else
      @num[:completed_questions] = test.ordered_questions.where('id < ?', current_question.id).count
      @num[:current_question] = @num[:completed_questions] + 1
    end

    @num
  end
end

app/controllers/tests_passages_controller.rb
class TestsPassagesController < ApplicationController
  before_action :authenticate_user!
  before_action :find_tests_passage, only: %i[show result update]

  def show; end

  def result; end

  def update
    @tests_passage.accept!(answer_ids)

    if @tests_passage.completed?
      TestsMailer.completed_test(@tests_passage).deliver_now
      redirect_to result_tests_passage_path(@tests_passage)
    else
      render :show
    end
  end

  private

  def find_tests_passage
    @tests_passage = TestsPassage.find(params[:tests_passage_id])
  end

  def answer_ids
    params[:answer_ids] ? params[:answer_ids].map(&:to_i) : []
  end
end

app/helpers/tests_passages_helper.rb
module TestsPassagesHelper
  def progress(tests_passage)
    "#{tests_passage.num[:current_question]} from #{tests_passage.num[:questions]}"
  end

  def percentage(tests_passage)
    number_to_percentage(tests_passage.percentage, precision: 1)
  end
end

app/views/tests_passages/_percentage.html.slim
- if @tests_passage.passed?
    div id="test_passed" #{percentage(@tests_passage)} PASSED
- else
    div id="test_failed" #{percentage(@tests_passage)} FAILED

app/views/tests_passages/result.html.slim
h1 #{@tests_passage.test.title} Test Result

h2= render 'percentage', tests_passage: @tests_passage

= link_to 'Back', tests_path

app/views/tests_passages/show.html.slim
h1 Passing the #{@tests_passage.test.title} Test
h2 progress: #{progress(@tests_passage)}

b= @tests_passage.current_question.body

=form_with url: tests_passage_path(@tests_passage), local: true, method: :put do |f|
  = f.collection_check_boxes :answer_ids, @tests_passage.current_question.answers, :id, :body, include_hidden: false do |b|
    p
      = b.check_box id: "answer_ids_#{b.object.id}"
      = b.label
  p= f.submit 'Next'