config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'user/registrations' }

  resources :tests, param: :test_id, only: :index do
    member do
      post :start
    end
  end

  resources :tests_passages, param: :tests_passage_id, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    root to: 'tests#index'
    resources :tests, param: :test_id do
      member do
        resources :questions, shallow: true, param: :question_id, except: :index do
          member do
            resources :answers, shallow: true, param: :answer_id, except: :index
          end
        end
      end
    end
  end
end

app/models/answer.rb
class Answer < ApplicationRecord
  MAX_NUMBER_ANSWERS = 4
  belongs_to :question

  # Question.take.answers.with_true_correctness
  scope :with_true_correctness, -> { where(correct: true) }

  validates :body, presence: true
  validate :validate_max_number_answers, on: :create

  private

  def validate_max_number_answers
    return false if question.answers.count < MAX_NUMBER_ANSWERS

    errors.add(:question_id, "too much anwers, #{MAX_NUMBER_ANSWERS} maximum")
  end
end

app/controllers/admin/answers_controller.rb
class Admin::AnswersController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_question, only: %i[new create]
  before_action :find_answer, only: %i[show edit update destroy]

  # GET /answers/1
  def show; end

  # GET /answers/new
  def new
    @answer = @question.answers.new
  end

  # GET /answers/1/edit
  def edit; end

  # POST /answers
  def create
    @answer = @question.answers.new(answer_params)

    if @answer.save
      redirect_to admin_answer_path(@answer), notice: 'Answer was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /answers/1
  def update
    if @answer.update(answer_params)
      redirect_to admin_answer_path(@answer), notice: 'Answer was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /answers/1
  def destroy
    @answer.destroy
    redirect_to admin_question_path(@answer.question),
                notice: 'Answer was successfully destroyed.'
  end

  private

  def find_question
    @question = Question.find(params[:question_id])
  end

  # Use callbacks to share common setup or constraints between actions.
  def find_answer
    @answer = Answer.find(params[:answer_id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def answer_params
    params.require(:answer).permit(:body, :correct)
  end
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/views/admin/answers/_answer.html.slim
li
  = answer.body
  br
  = link_to 'Show', admin_answer_path(answer)
  = ' | '
  = link_to 'Edit', edit_admin_answer_path(answer)
  = ' | '
  = link_to 'Delete',
            admin_answer_path(answer),
            method: :delete,
            data: {confirm: 'Are you sure?'}

app/views/admin/answers/_form.html.slim
= form_with model: [:admin, @answer], local:true do |f|
  = render 'shared/errors_count_msg', resource: @answer
  p
    = f.label :body
    = f.text_area :body, rows: 4, cows: 60
    div= @answer.errors.messages[:body].join(', ')
  p
    = f.label :correct
    = f.check_box :correct, id: :answer_correct
    div= @answer.errors.messages[:correct].join(', ')
  = f.submit

app/views/admin/answers/edit.html.slim
h1 Editing Answer
p= @answer.question.body

= render 'form', answer: @answer
= link_to 'Back', admin_question_path(@answer.question)

app/views/admin/answers/new.html.slim
h1 New Answer
p= @question.body

= render 'form', answer: @answer
= link_to 'Back', admin_question_path(@question)

app/views/admin/answers/show.html.slim
h1 Question

p= @answer.question.body

p
  b Answer:
  =< @answer.body
p
  b Correct:
  =< @answer.correct

= link_to 'Edit', edit_admin_answer_path(@answer)
= ' | '
= link_to 'Back', admin_question_path(@answer.question)