config/routes.rb
Rails.application.routes.draw do
  root to: 'tests#index'

  devise_for :users, path: :gurus,
                     path_names: { sign_in: :login, sign_out: :logout },
                     controllers: { registrations: 'user/registrations' }

  resources :tests, param: :test_id, only: :index do
    member do
      post :start
    end
  end

  resources :tests_passages, param: :tests_passage_id, only: %i[show update] do
    member do
      get :result
    end
  end

  namespace :admin do
    root to: 'tests#index'
    resources :tests, param: :test_id do
      member do
        resources :questions, shallow: true, param: :question_id, except: :index do
          member do
            resources :answers, shallow: true, param: :answer_id, except: :index
          end
        end
      end
    end
  end
end

app/models/question.rb
class Question < ApplicationRecord
  belongs_to :test
  has_many :answers, dependent: :destroy

  validates :body, presence: true
end

app/controllers/admin/questions_controller.rb
class Admin::QuestionsController < Admin::BaseController
  before_action :authenticate_user!
  before_action :find_question_and_set_test, only: %i[show destroy edit update]
  before_action :find_test, only: %i[create new]
  before_action :find_answers, only: %i[show]
  rescue_from ActiveRecord::RecordNotFound, with: :rescue_with_question_not_found

  def create
    @question = @test.questions.new(question_params)
    if @question.save
      redirect_to admin_question_path(@question)
    else
      render plain: 'Question Not Create', status: :bad_request
    end
  end

  def edit; end

  def update
    if @question.update(question_params)
      redirect_to admin_question_path(@question)
    else
      render plain: 'Question Not Update', status: :bad_request
    end
  end

  def new
    @question = @test.questions.new
  end

  def show; end

  def destroy
    @question.destroy
    redirect_to @test
  end

  private

  def question_params
    params.require(:question).permit(:body)
  end

  def find_test
    @test = Test.find(params[:test_id])
  end

  def find_question_and_set_test
    @question = Question.find(params[:question_id])
    @test = @question.test
  end

  def rescue_with_question_not_found
    render plain: 'Question Not Found', status: :not_found
  end

  def find_answers
    @answers = @question.answers
  end
end

app/helpers/admin/questions_helper.rb
module Admin::QuestionsHelper
  HEADER_TEXT = {
    new: 'Create New %s Question',
    edit: 'Edit %s Question'
  }.freeze

  # Create New <Test Title> Question, а в форме редактирования Edit <Test Title> Question
  def header_text(question)
    header = question.new_record? ? HEADER_TEXT[:new] : HEADER_TEXT[:edit]
    format(header, question.test.title)
  end
end

app/views/admin/questions/_form.html.slim
= form_with model: [:admin, @question] do |f|
  p
    | Question body: #{f.text_field :body}
  = f.submit

app/views/admin/questions/_question.html.slim
tr
  td= question.body
  td= link_to 'Show', admin_question_path(question)
  td= link_to 'Edit', edit_admin_question_path(question)
  td= link_to 'Delete',\
      admin_question_path(question),\
      method: :delete,\
      data: { confirm: 'Are you sure?' }

app/views/admin/questions/_question_header.html.slim
h1 #{header_text(@question)}

app/views/admin/questions/_questions_table.html.slim
table
  tr
    th Question
    th colspan="3" Actions
  = render @questions

app/views/admin/questions/destroy.html.slim
h1 Questions#destroy
p question #{@question.body} destroyed

app/views/admin/questions/edit.html.slim
=render 'question_header'
=render 'form'

app/views/admin/questions/new.html.slim
=render 'question_header'
=render 'form'

app/views/admin/questions/show.html.slim
h1= @test.title
p= @question.body

h2 Answers

= link_to 'New answer', new_admin_answer_path(@question)

ol= render @question.answers

= link_to 'Edit', edit_admin_question_path(@question)
= ' | '
= link_to 'Back', admin_test_path(@question.test)